server:
  port: 8090

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://gdmt-ms-eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: /
  zipkin:
    baseUrl: http://gdmt-ms-zipkin-server:9411

zuul:
  routes:
    gdmt-ms-identitymanagement-neg:
      service-id: gdmt-ms-identitymanagement-neg
      path: /gdmt-ms-identitymanagement-neg/**

    gdmt-ms-logicalfolders-neg:
      service-id: gdmt-ms-logicalfolders-neg
      path: /gdmt-ms-logicalfolders-neg/**

    gdmt-ms-retentionschedules-neg:
      service-id: gdmt-ms-retentionschedules-neg
      path: /gdmt-ms-retentionschedules-neg/**

    gdmt-ms-oauth2-server:
      service-id: gdmt-ms-oauth2-server
      path: /gdmt-ms-oauth2-server/**
      sensitive-headers: Cookie,Set-Cookie

    gdmt-ms-frontendconfiguration-utl:
      service-id: gdmt-ms-frontendconfiguration-utl
      path: /gdmt-ms-frontendconfiguration-utl/**