server:
  port: 8080

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://gdmt-ms-eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
  datasource:
    url: ${gdmt.datasource.url}
    username: ${gdmt.datasource.username}
    password: ${gdmt.datasource.password}
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://gdmt-ms-zipkin-server:9411

application:
  permissionsSettings:
    enabled: true
    objectType: DOCUMENT_TYPE
    permissions:
      createDocumentType: CREATE_DOCUMENT_TYPE
      readDocumentType: READ_DOCUMENT_TYPE
      updateDocumentType: UPDATE_DOCUMENT_TYPE
      deleteDocumentType: DELETE_DOCUMENT_TYPE
      manageDocumentType: MANAGE_DOCUMENT_TYPE
  errors:
    documentTypeNotFound:
      code: GDMT_RSN_001
      message: Document type not found.
    fieldNotFound:
      code: GDMT_RSN_002
      message: Field not found.
    fieldAlreadyExists:
      code: GDMT_RSN_003
      message: Field already exists.
    documentTypeAlreadyExists:
      code: GDMT_RSN_004
      message: Document type already exists.
    itIsCaseFileCannotBeActivated:
      code: GDMT_RSN_005
      message: The "It is a case file" option cannot be activated because there are associated documents for this document type.
    itIsCaseFileCannotBeDeactivated:
      code: GDMT_RSN_006
      message: The "It is a case file" option cannot be deactivated because there are associated documents for this document type.
    daysToMoveToTrashNotPermitted:
      code: GDMT_RSN_007
      message: The days designated for moving the document to trash must exceed the number of days for blocking the document.
    daysToDeleteNotPermitted:
      code: GDMT_RSN_008
      message: The days designated for deleting the document must exceed the number of days for moving the document to trash.
    retentionDaysCannotBeZero:
      code: GDMT_RSN_009
      message: The retention days cannot be zero.

data-provider:
  rest:
    gdmt-ms-identitymanagement-neg:
      baseUrl: http://gdmt-ms-identitymanagement-neg-re-v1-0/api/v1.0
      operations:
        findAllGroups: ${data-provider.rest.gdmt-ms-identitymanagement-neg.baseUrl}/groups
        findAllPermissions: ${data-provider.rest.gdmt-ms-identitymanagement-neg.baseUrl}/permissions
    gdmt-ms-documents-neg:
      baseUrl: https://mock-ms-documents-neg.wiremockapi.cloud/gdmt-ms-documents-neg/api/develop
      operations:
        findAllDocuments: ${data-provider.rest.gdmt-ms-documents-neg.baseUrl}/documents